// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pufeoudksymvpnqdblrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1ZmVvdWRrc3ltdnBucWRibHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTc3MDcsImV4cCI6MjA2NDAzMzcwN30.L2lTE2kssMhQv_a-t3njSVg7uJ3zWIsBY7R9LpduLzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);